[platformio]
default_envs = native

[env:native]
platform = https://github.com/meshtastic/platform-native.git
build_flags =
  ${env.build_flags}
  -O0
  -li2c
  -lmbedtls
  -lmbedx509
  -lmbedcrypto
framework = arduino
board = linux_hardware




